### ISSUE TITLE
running with nohup

### ISSUE THREAD

**Issue by emgiles** [wbazant/eukprot-alignments-nextflow#9]
Is it possible to run run.sh with nohup? I have tried this, it starts, then nohup stopped, but nextflow and java processes show with htop. I don't know if my run is working or not. Subdirectory work is created along with trace.txt.
Any advice would be great!

**Comment by emgiles** [comment]
Never mind, I changed the resource configuration file 

process {
  maxForks = 3

  withLabel: 'align' {
    errorStrategy = 'finish'
  }
}process {
  maxForks = 3

  withLabel: 'align' {
    errorStrategy = 'finish'
  }
}

as per your comment in another issue thread and it seems to work now. Thanks

**Comment by wbazant** [comment]
This sounds like a Nextflow question but I can have a go, what are you trying to do?

Changing errorStrategy is good for adapting the pipeline's behaviour when individual jobs are failing. 'finish' is good for not throwing away partially done work due to an intermittent failure, there's even a setting to ignore failed jobs and proceed with the rest of the work that you can try if you feel you understand why the alignments fail.

On the other hand, if you're connecting to a cluster via SSH and don't want the connection drop to kill nextflow - I think nohup would work, I've never used it, but it doesn't seem very convenient because you want the pipeline manager to stay responsive, so you can kill it if you need to. I used to run pipelines inside a `screen` on the cluster, you could try that - after you SSH, init a `screen` or `tmux` session, then you can disconnect or your SSH can drop, and you can come back and reattach later.

**Comment by emgiles** [comment]
Hi again
Thanks a lot for the info. I don't have any issues with nohup now, CORRAL seems to be working find now.
